ult: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5


production:
  adapter: postgresql
  prepared_statements: false
  advisory_locks: false
